# Generated by Django 5.0.4 on 2024-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='peopleRequired',
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued')], default='OPEN', max_length=12),
        ),
    ]
