# Generated by Django 5.0.4 on 2024-04-28 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_remove_commission_peoplerequired_commission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('manpowerRequired', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full')], default='OPEN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='commissions.commission')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['status', '-manpowerRequired', 'role'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
