# Generated by Django 5.0.4 on 2024-05-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_alter_jobapplication_status'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_at'], 'verbose_name': 'Commission', 'verbose_name_plural': 'Commissions'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['status', '-applied_at'], 'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AddField(
            model_name='commission',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('AO', 'Open'), ('BF', 'Full'), ('CC', 'Completed'), ('DD', 'Discontinued')], default='AO', max_length=13),
        ),
    ]
