# Generated by Django 5.0.4 on 2024-05-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_alter_commission_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='openManpower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='openManpower',
            field=models.IntegerField(default=0),
        ),
    ]
