# Generated by Django 5.0.4 on 2024-05-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_commission_currentmanpower_job_currentmanpower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='currentManpower',
        ),
        migrations.RemoveField(
            model_name='job',
            name='currentManpower',
        ),
        migrations.AddField(
            model_name='commission',
            name='openManpower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='openManpower',
            field=models.IntegerField(default=0),
        ),
    ]
