# Generated by Django 5.0.4 on 2024-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_remove_commission_currentmanpower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
